### ISSUE TITLE
Build the logic for adding daily routinue and task 

### ISSUE THREAD

**Issue by praveen4star** [Praveengupta1/Tracker#17]
Like a ToDo App, we can  add daily life's rountinue
 and also We can add daily task like google calendar.

**Comment by goutham03062001** [comment]
Hey, I would like to work upon this issue. 

What exactly you want to achieve? Just to implement the functionality to add daily life's routine or should I implement the reminder functionality also? 

Hope to receive your feedback ASAP.

**Comment by praveen4star** [comment]
Thanks @goutham03062001  for your interest.
 Reminder is also a functionality.

**Comment by goutham03062001** [comment]
Hey thank you for the feedback.

So, shall i send reminder to the email? It would be very easy. Or do you have anything in mind. Please share your thoughts here.

**Comment by goutham03062001** [comment]
Hello, your dashboard branch is behind some commits.

I'm unable to fork the repo with the new changes you have 4 days ago. Please  look into this issue and resolve as soon as possible.
